### ISSUE TITLE
Alternate high-contrast colours and font sizes

### ISSUE THREAD

**Issue by EndingCredits** [fghaas/cookiecutter-presentation#1]
Some people with certain vision impairments benefit from high contrast colours other than black/white, one particular example being black/yellow (although, unfortunately I couldn't find a particular reference for this). Additionally large font sizes obviously benefit many users with poor vision.

I would expect most users with these requirement will already be using some form of in-built accessibility option, but perhaps this could be directly incorporated as an option for the online slide notes, e.g. see the bottom of the nav-bar of https://retinauk.org.uk/ ?

Best,
Will

**Comment by fghaas** [comment]
Sorry for missing this issue; I *think* I fixed this by exposing the theme switch via the menu plugin in bbebef3a6d3c7c1fd03a28aa60e73001192edcb9 a few months ago. Would you mind taking a look to see if that helps?

**Comment by EndingCredits** [comment]
Is there a demo available online? Otherwise I'll have a look at generating a test presentation.

**Comment by fghaas** [comment]
Sure, https://fghaas.github.io/cookiecutter-presentation (click the ☰ button or type `m`, then click the 🌓 symbol and select your preferred theme).

**Comment by EndingCredits** [comment]
Only major suggestion I have is, if it's easy to do a yellow-text-on-black theme, that might be quite helpful.

Otherwise, it's a bit fiddly (bit worried people won't be able to find it / be aware it exists), but I think it works as a solution!

**Comment by fghaas** [comment]
For the cookiecutter I don't define my own themes; I use the themes from reveal.js instead. The available themes are in https://github.com/hakimel/reveal.js/tree/master/css/theme/source — maybe you'd like to submit a PR for a yellow-on-black theme there?

**Comment by EndingCredits** [comment]
Okay, will do.

**Comment by fghaas** [comment]
Excellent, thanks! I think it might even be as simple as taking https://github.com/hakimel/reveal.js/blob/master/css/theme/source/white.scss, copy it as `yellow.scss`, then set `$backgroundColor: #ffff00;` and `$mainColor: #000;` and you might be on your way. :)
